export const countries = [
  { name: "Afghanistan", continent: "Asia", flagColors: ["black", "red", "green", "white"], flagImage: "images/afghanistan.png" },
  { name: "Albania", continent: "Europe", flagColors: ["red", "black"], flagImage: "images/albania.png" },
  { name: "Algeria", continent: "Africa", flagColors: ["green", "white", "red"], flagImage: "images/algeria.png" },
  { name: "Andorra", continent: "Europe", flagColors: ["blue", "yellow", "red"], flagImage: "images/andorra.png" },
  { name: "Angola", continent: "Africa", flagColors: ["red", "black", "yellow"], flagImage: "images/angola.png" },
  { name: "Antigua and Barbuda", continent: "North-America", flagColors: ["red", "white", "blue", "black", "yellow"], flagImage: "images/antigua-and-barbuda.png" },
  { name: "Argentina", continent: "South-America", flagColors: ["blue", "white", "yellow"], flagImage: "images/argentina.png" },
  { name: "Armenia", continent: "Asia", flagColors: ["red", "blue", "orange"], flagImage: "images/armenia.png" },
  { name: "Australia", continent: "Oceania", flagColors: ["blue", "white", "red"], flagImage: "images/australia.png" },
  { name: "Austria", continent: "Europe", flagColors: ["red", "white"], flagImage: "images/austria.png" },
  { name: "Azerbaijan", continent: "Asia", flagColors: ["blue", "red", "green", "white"], flagImage: "images/azerbaijan.png" },
  { name: "Bahamas", continent: "North-America", flagColors: ["blue", "yellow", "black"], flagImage: "images/bahamas.png" },
  { name: "Bahrain", continent: "Asia", flagColors: ["red", "white"], flagImage: "images/bahrain.png" },
  { name: "Bangladesh", continent: "Asia", flagColors: ["green", "red"], flagImage: "images/bangladesh.png" },
  { name: "Barbados", continent: "North-America", flagColors: ["blue", "yellow", "black"], flagImage: "images/barbados.png" },
  { name: "Belarus", continent: "Europe", flagColors: ["red", "green", "white"], flagImage: "images/belarus.png" },
  { name: "Belgium", continent: "Europe", flagColors: ["black", "yellow", "red"], flagImage: "images/belgium.png" },
  { name: "Belize", continent: "North-America", flagColors: ["blue", "red", "white"], flagImage: "images/belize.png" },
  { name: "Benin", continent: "Africa", flagColors: ["green", "yellow", "red"], flagImage: "images/benin.png" },
  { name: "Bhutan", continent: "Asia", flagColors: ["yellow", "orange", "white"], flagImage: "images/bhutan.png" },
  { name: "Bolivia", continent: "South-America", flagColors: ["red", "yellow", "green"], flagImage: "images/bolivia.png" },
  { name: "Bosnia and Herzegovina", continent: "Europe", flagColors: ["blue", "yellow", "white"], flagImage: "images/bosnia-and-herzegovina.png" },
  { name: "Botswana", continent: "Africa", flagColors: ["blue", "white", "black"], flagImage: "images/botswana.png" },
  { name: "Brazil", continent: "South-America", flagColors: ["green", "yellow", "blue", "white"], flagImage: "images/brazil.png" },
  { name: "Brunei", continent: "Asia", flagColors: ["yellow", "white", "black", "red"], flagImage: "images/brunei.png" },
  { name: "Bulgaria", continent: "Europe", flagColors: ["white", "green", "red"], flagImage: "images/bulgaria.png" },
  { name: "Burkina Faso", continent: "Africa", flagColors: ["red", "green", "yellow"], flagImage: "images/burkina-faso.png" },
  { name: "Burundi", continent: "Africa", flagColors: ["red", "white", "green"], flagImage: "images/burundi.png" },
  { name: "Cabo Verde", continent: "Africa", flagColors: ["blue", "white", "red", "yellow"], flagImage: "images/cabo-verde.png" },
  { name: "Cambodia", continent: "Asia", flagColors: ["blue", "red", "white"], flagImage: "images/cambodia.png" },
  { name: "Cameroon", continent: "Africa", flagColors: ["green", "red", "yellow"], flagImage: "images/cameroon.png" },
  { name: "Canada", continent: "North-America", flagColors: ["red", "white"], flagImage: "images/canada.png" },
  { name: "Central African Republic", continent: "Africa", flagColors: ["blue", "white", "green", "yellow", "red"], flagImage: "images/central-african-republic.png" },
  { name: "Chad", continent: "Africa", flagColors: ["blue", "yellow", "red"], flagImage: "images/chad.png" },
  { name: "Chile", continent: "South-America", flagColors: ["red", "white", "blue"], flagImage: "images/chile.png" },
  { name: "China", continent: "Asia", flagColors: ["red", "yellow"], flagImage: "images/china.png" },
  { name: "Colombia", continent: "South-America", flagColors: ["yellow", "blue", "red"], flagImage: "images/colombia.png" },
  { name: "Comoros", continent: "Africa", flagColors: ["yellow", "white", "red", "blue", "green"], flagImage: "images/comoros.png" },
  { name: "Republic of the Congo", continent: "Africa", flagColors: ["green", "yellow", "red"], flagImage: "images/republic-of-the-congo.png" },
  { name: "Congo (DRC)", continent: "Africa", flagColors: ["blue", "yellow", "red"], flagImage: "images/congo-drc.png" },
  { name: "Costa Rica", continent: "North-America", flagColors: ["blue", "white", "red"], flagImage: "images/costa-rica.png" },
  { name: "Croatia", continent: "Europe", flagColors: ["red", "white", "blue"], flagImage: "images/croatia.png" },
  { name: "Cuba", continent: "North-America", flagColors: ["blue", "white", "red"], flagImage: "images/cuba.png" },
  { name: "Cyprus", continent: "Europe", flagColors: ["white", "orange", "green"], flagImage: "images/cyprus.png" },
  { name: "Czech Republic", continent: "Europe", flagColors: ["white", "blue", "red"], flagImage: "images/czech-republic.png" },
  { name: "Denmark", continent: "Europe", flagColors: ["red", "white"], flagImage: "images/denmark.png" },
  { name: "Djibouti", continent: "Africa", flagColors: ["blue", "green", "white", "red"], flagImage: "images/djibouti.png" },
  { name: "Dominica", continent: "North-America", flagColors: ["green", "yellow", "black", "white", "red"], flagImage: "images/dominica.png" },
  { name: "Dominican Republic", continent: "North-America", flagColors: ["blue", "red", "white"], flagImage: "images/dominican-republic.png" },
  { name: "Ecuador", continent: "South-America", flagColors: ["yellow", "blue", "red"], flagImage: "images/ecuador.png" },
  { name: "Egypt", continent: "Africa", flagColors: ["red", "white", "black", "gold"], flagImage: "images/egypt.png" },
  { name: "El Salvador", continent: "North-America", flagColors: ["blue", "white"], flagImage: "images/el-salvador.png" },
  { name: "Equatorial Guinea", continent: "Africa", flagColors: ["green", "white", "red", "blue"], flagImage: "images/equatorial-guinea.png" },
  { name: "Eritrea", continent: "Africa", flagColors: ["green", "red", "blue", "yellow"], flagImage: "images/eritrea.png" },
  { name: "Estonia", continent: "Europe", flagColors: ["blue", "black", "white"], flagImage: "images/estonia.png" },
  { name: "Eswatini", continent: "Africa", flagColors: ["blue", "yellow", "red"], flagImage: "images/eswatini.png" },
  { name: "Ethiopia", continent: "Africa", flagColors: ["green", "yellow", "red", "blue"], flagImage: "images/ethiopia.png" },
  { name: "Fiji", continent: "Oceania", flagColors: ["blue", "white", "red"], flagImage: "images/fiji.png" },
  { name: "Finland", continent: "Europe", flagColors: ["white", "blue"], flagImage: "images/finland.png" },
  { name: "France", continent: "Europe", flagColors: ["blue", "white", "red"], flagImage: "images/france.png" },
  { name: "Gabon", continent: "Africa", flagColors: ["green", "yellow", "blue"], flagImage: "images/gabon.png" },
  { name: "Gambia", continent: "Africa", flagColors: ["red", "blue", "green", "white"], flagImage: "images/gambia.png" },
  { name: "Georgia", continent: "Asia", flagColors: ["white", "red"], flagImage: "images/georgia.png" },
  { name: "Germany", continent: "Europe", flagColors: ["black", "red", "yellow"], flagImage: "images/germany.png" },
  { name: "Ghana", continent: "Africa", flagColors: ["red", "yellow", "green", "black"], flagImage: "images/ghana.png" },
  { name: "Greece", continent: "Europe", flagColors: ["blue", "white"], flagImage: "images/greece.png" },
  { name: "Grenada", continent: "North-America", flagColors: ["red", "yellow", "green"], flagImage: "images/grenada.png" },
  { name: "Guatemala", continent: "North-America", flagColors: ["blue", "white"], flagImage: "images/guatemala.png" },
  { name: "Guinea", continent: "Africa", flagColors: ["red", "yellow", "green"], flagImage: "images/guinea.png" },
  { name: "Guinea-Bissau", continent: "Africa", flagColors: ["red", "yellow", "green", "black"], flagImage: "images/guinea-bissau.png" },
  { name: "Guyana", continent: "South-America", flagColors: ["green", "yellow", "red", "black", "white"], flagImage: "images/guyana.png" },
  { name: "Haiti", continent: "North-America", flagColors: ["blue", "red"], flagImage: "images/haiti.png" },
  { name: "Honduras", continent: "North-America", flagColors: ["blue", "white"], flagImage: "images/honduras.png" },
  { name: "Hungary", continent: "Europe", flagColors: ["red", "white", "green"], flagImage: "images/hungary.png" },
  { name: "Iceland", continent: "Europe", flagColors: ["blue", "white", "red"], flagImage: "images/iceland.png" },
  { name: "India", continent: "Asia", flagColors: ["orange", "white", "green", "blue"], flagImage: "images/india.png" },
  { name: "Indonesia", continent: "Asia", flagColors: ["red", "white"], flagImage: "images/indonesia.png" },
  { name: "Iran", continent: "Asia", flagColors: ["green", "white", "red"], flagImage: "images/iran.png" },
  { name: "Iraq", continent: "Asia", flagColors: ["red", "white", "black", "green"], flagImage: "images/iraq.png" },
  { name: "Ireland", continent: "Europe", flagColors: ["green", "white", "orange"], flagImage: "images/ireland.png" },
  { name: "Israel", continent: "Asia", flagColors: ["white", "blue"], flagImage: "images/israel.png" },
  { name: "Italy", continent: "Europe", flagColors: ["green", "white", "red"], flagImage: "images/italy.png" },
  { name: "Ivory Coast", continent: "Africa", flagColors: ["orange", "white", "green"], flagImage: "images/ivory-coast.png" },
  { name: "Jamaica", continent: "North-America", flagColors: ["green", "yellow", "black"], flagImage: "images/jamaica.png" },
  { name: "Japan", continent: "Asia", flagColors: ["white", "red"], flagImage: "images/japan.png" },
  { name: "Jordan", continent: "Asia", flagColors: ["black", "white", "green", "red"], flagImage: "images/jordan.png" },
  { name: "Kazakhstan", continent: "Asia", flagColors: ["blue", "yellow"], flagImage: "images/kazakhstan.png" },
  { name: "Kenya", continent: "Africa", flagColors: ["black", "red", "green", "white"], flagImage: "images/kenya.png" },
  { name: "Kiribati", continent: "Oceania", flagColors: ["red", "white", "blue", "yellow"], flagImage: "images/kiribati.png" },
  { name: "Kosovo", continent: "Europe", flagColors: ["blue", "yellow", "white"], flagImage: "images/kosovo.png" },
  { name: "Kuwait", continent: "Asia", flagColors: ["green", "white", "red", "black"], flagImage: "images/kuwait.png" },
  { name: "Kyrgyzstan", continent: "Asia", flagColors: ["red", "yellow"], flagImage: "images/kyrgyzstan.png" },
  { name: "Laos", continent: "Asia", flagColors: ["red", "blue", "white"], flagImage: "images/laos.png" },
  { name: "Latvia", continent: "Europe", flagColors: ["red", "white"], flagImage: "images/latvia.png" },
  { name: "Lebanon", continent: "Asia", flagColors: ["red", "white", "green"], flagImage: "images/lebanon.png" },
  { name: "Lesotho", continent: "Africa", flagColors: ["blue", "white", "green", "black"], flagImage: "images/lesotho.png" },
  { name: "Liberia", continent: "Africa", flagColors: ["red", "white", "blue"], flagImage: "images/liberia.png" },
  { name: "Libya", continent: "Africa", flagColors: ["red", "black", "green", "white"], flagImage: "images/libya.png" },
  { name: "Liechtenstein", continent: "Europe", flagColors: ["blue", "red", "yellow"], flagImage: "images/liechtenstein.png" },
  { name: "Lithuania", continent: "Europe", flagColors: ["yellow", "green", "red"], flagImage: "images/lithuania.png" },
  { name: "Luxembourg", continent: "Europe", flagColors: ["red", "white", "blue"], flagImage: "images/luxembourg.png" },
  { name: "Madagadar", continent: "Africa", flagColors: ["white", "red", "green"], flagImage: "images/madagascar.png" },
  { name: "Malawi", continent: "Africa", flagColors: ["black", "red", "green"], flagImage: "images/malawi.png" },
  { name: "Malaysia", continent: "Asia", flagColors: ["red", "white", "blue", "yellow"], flagImage: "images/malaysia.png" },
  { name: "Maldives", continent: "Asia", flagColors: ["red", "green", "white"], flagImage: "images/maldives.png" },
  { name: "Mali", continent: "Africa", flagColors: ["green", "yellow", "red"], flagImage: "images/mali.png" },
  { name: "Malta", continent: "Europe", flagColors: ["white", "red"], flagImage: "images/malta.png" },
  { name: "Marshall Islands", continent: "Oceania", flagColors: ["blue", "white", "orange"], flagImage: "images/marshall-islands.png" },
  { name: "Mauritania", continent: "Africa", flagColors: ["green", "yellow", "red"], flagImage: "images/mauritania.png" },
  { name: "Mauritius", continent: "Africa", flagColors: ["red", "blue", "yellow", "green"], flagImage: "images/mauritius.png" },
  { name: "Mexico", continent: "North-America", flagColors: ["green", "white", "red"], flagImage: "images/mexico.png" },
  { name: "Micronesia", continent: "Oceania", flagColors: ["blue", "white"], flagImage: "images/micronesia.png" },
  { name: "Moldova", continent: "Europe", flagColors: ["blue", "yellow", "red"], flagImage: "images/moldova.png" },
  { name: "Monaco", continent: "Europe", flagColors: ["red", "white"], flagImage: "images/monaco.png" },
  { name: "Mongolia", continent: "Asia", flagColors: ["red", "blue", "yellow"], flagImage: "images/mongolia.png" },
  { name: "Montenegro", continent: "Europe", flagColors: ["red", "gold"], flagImage: "images/montenegro.png" },
  { name: "Morocco", continent: "Africa", flagColors: ["red", "green"], flagImage: "images/morocco.png" },
  { name: "Mozambique", continent: "Africa", flagColors: ["green", "black", "yellow", "white", "red"], flagImage: "images/mozambique.png" },
  { name: "Myanmar", continent: "Asia", flagColors: ["yellow", "green", "red", "white"], flagImage: "images/myanmar.png" },
  { name: "Namibia", continent: "Africa", flagColors: ["blue", "red", "green", "white", "yellow"], flagImage: "images/namibia.png" },
  { name: "Nauru", continent: "Oceania", flagColors: ["blue", "yellow", "white"], flagImage: "images/nauru.png" },
  { name: "Nepal", continent: "Asia", flagColors: ["red", "blue", "white"], flagImage: "images/nepal.png" },
  { name: "Netherlands", continent: "Europe", flagColors: ["red", "white", "blue"], flagImage: "images/netherlands.png" },
  { name: "New Zealand", continent: "Oceania", flagColors: ["blue", "red", "white"], flagImage: "images/new-zealand.png" },
  { name: "Nicaragua", continent: "North-America", flagColors: ["blue", "white"], flagImage: "images/nicaragua.png" },
  { name: "Niger", continent: "Africa", flagColors: ["orange", "white", "green"], flagImage: "images/niger.png" },
  { name: "Nigeria", continent: "Africa", flagColors: ["green", "white"], flagImage: "images/nigeria.png" },
  { name: "North Korea", continent: "Asia", flagColors: ["blue", "white", "red"], flagImage: "images/north-korea.png" },
  { name: "North Macedonia", continent: "Europe", flagColors: ["red", "yellow"], flagImage: "images/north-macedonia.png" },
  { name: "Norway", continent: "Europe", flagColors: ["red", "white", "blue"], flagImage: "images/norway.png" },
  { name: "Oman", continent: "Asia", flagColors: ["red", "white", "green"], flagImage: "images/oman.png" },
  { name: "Pakistan", continent: "Asia", flagColors: ["green", "white"], flagImage: "images/pakistan.png" },
  { name: "Palau", continent: "Oceania", flagColors: ["blue", "yellow"], flagImage: "images/palau.png" },
  { name: "Palestine", continent: "Asia", flagColors: ["black", "white", "green", "red"], flagImage: "images/palestine.png" },
  { name: "Panama", continent: "North-America", flagColors: ["white", "red", "blue"], flagImage: "images/panama.png" },
  { name: "Papua New Guinea", continent: "Oceania", flagColors: ["red", "black", "yellow", "white"], flagImage: "images/papua-new-guinea.png" },
  { name: "Paraguay", continent: "South-America", flagColors: ["red", "white", "blue"], flagImage: "images/paraguay.png" },
  { name: "Peru", continent: "South-America", flagColors: ["red", "white"], flagImage: "images/peru.png" },
  { name: "Philippines", continent: "Asia", flagColors: ["blue", "red", "white", "yellow"], flagImage: "images/philippines.png" },
  { name: "Poland", continent: "Europe", flagColors: ["white", "red"], flagImage: "images/poland.png" },
  { name: "Portugal", continent: "Europe", flagColors: ["green", "red", "yellow"], flagImage: "images/portugal.png" },
  { name: "Qatar", continent: "Asia", flagColors: ["white", "maroon"], flagImage: "images/qatar.png" },
  { name: "Romania", continent: "Europe", flagColors: ["blue", "yellow", "red"], flagImage: "images/romania.png" },
  { name: "Russia", continent: "Europe", flagColors: ["white", "blue", "red"], flagImage: "images/russia.png" },
  { name: "Rwanda", continent: "Africa", flagColors: ["blue", "yellow", "green"], flagImage: "images/rwanda.png" },
  { name: "Saint Kitts and Nevis", continent: "North-America", flagColors: ["green", "red", "yellow", "black", "white"], flagImage: "images/saint-kitts-and-nevis.png" },
  { name: "Saint Lucia", continent: "North-America", flagColors: ["blue", "yellow", "black", "white"], flagImage: "images/saint-lucia.png" },
  { name: "Saint Vincent and the Grenadines", continent: "North-America", flagColors: ["blue", "green", "yellow"], flagImage: "images/saint-vincent-and-the-grenadines.png" },
  { name: "Samoa", continent: "Oceania", flagColors: ["red", "blue", "white"], flagImage: "images/samoa.png" },
  { name: "San Marino", continent: "Europe", flagColors: ["white", "blue"], flagImage: "images/san-marino.png" },
  { name: "Sao Tome and Principe", continent: "Africa", flagColors: ["green", "yellow", "red", "black"], flagImage: "images/sao-tome-and-principe.png" },
  { name: "Saudi Arabia", continent: "Asia", flagColors: ["green", "white"], flagImage: "images/saudi-arabia.png" },
  { name: "Senegal", continent: "Africa", flagColors: ["green", "yellow", "red"], flagImage: "images/senegal.png" },
  { name: "Serbia", continent: "Europe", flagColors: ["red", "blue", "white"], flagImage: "images/serbia.png" },
  { name: "Seychelles", continent: "Africa", flagColors: ["blue", "yellow", "red", "white", "green"], flagImage: "images/seychelles.png" },
  { name: "Sierra Leone", continent: "Africa", flagColors: ["green", "white", "blue"], flagImage: "images/sierra-leone.png" },
  { name: "Singapore", continent: "Asia", flagColors: ["red", "white"], flagImage: "images/singapore.png" },
  { name: "Slovakia", continent: "Europe", flagColors: ["white", "blue", "red"], flagImage: "images/slovakia.png" },
  { name: "Slovenia", continent: "Europe", flagColors: ["white", "blue", "red"], flagImage: "images/slovenia.png" },
  { name: "Solomon Islands", continent: "Oceania", flagColors: ["blue", "green", "yellow", "white"], flagImage: "images/solomon-islands.png" },
  { name: "Somalia", continent: "Africa", flagColors: ["blue", "white"], flagImage: "images/somalia.png" },
  { name: "South Africa", continent: "Africa", flagColors: ["red", "blue", "green", "yellow", "black", "white"], flagImage: "images/south-africa.png" },
  { name: "South Korea", continent: "Asia", flagColors: ["white", "red", "blue", "black"], flagImage: "images/south-korea.png" },
  { name: "South Sudan", continent: "Africa", flagColors: ["black", "red", "green", "blue", "yellow", "white"], flagImage: "images/south-sudan.png" },
  { name: "Spain", continent: "Europe", flagColors: ["red", "yellow"], flagImage: "images/spain.png" },
  { name: "Sri Lanka", continent: "Asia", flagColors: ["orange", "green", "yellow", "red"], flagImage: "images/sri-lanka.png" },
  { name: "Sudan", continent: "Africa", flagColors: ["red", "white", "black", "green"], flagImage: "images/sudan.png" },
  { name: "Suriname", continent: "South-America", flagColors: ["green", "white", "red", "yellow"], flagImage: "images/suriname.png" },
  { name: "Sweden", continent: "Europe", flagColors: ["blue", "yellow"], flagImage: "images/sweden.png" },
  { name: "Switzerland", continent: "Europe", flagColors: ["red", "white"], flagImage: "images/switzerland.png" },
  { name: "Syria", continent: "Asia", flagColors: ["red", "white", "black", "green"], flagImage: "images/syria.png" },
  { name: "Taiwan", continent: "Asia", flagColors: ["red", "blue", "white"], flagImage: "images/taiwan.png" },
  { name: "Tajikistan", continent: "Asia", flagColors: ["red", "white", "green"], flagImage: "images/tajikistan.png" },
  { name: "Tanzania", continent: "Africa", flagColors: ["green", "yellow", "blue", "black"], flagImage: "images/tanzania.png" },
  { name: "Thailand", continent: "Asia", flagColors: ["red", "white", "blue"], flagImage: "images/thailand.png" },
  { name: "Timor-Leste", continent: "Asia", flagColors: ["red", "yellow", "black", "white"], flagImage: "images/timor-leste.png" },
  { name: "Togo", continent: "Africa", flagColors: ["green", "yellow", "red", "white"], flagImage: "images/togo.png" },
  { name: "Tonga", continent: "Oceania", flagColors: ["red", "white"], flagImage: "images/tonga.png" },
  { name: "Trinidad and Tobago", continent: "North-America", flagColors: ["red", "white", "black"], flagImage: "images/trinidad-and-tobago.png" },
  { name: "Tunisia", continent: "Africa", flagColors: ["red", "white"], flagImage: "images/tunisia.png" },
  { name: "Turkey", continent: "Asia", flagColors: ["red", "white"], flagImage: "images/turkey.png" },
  { name: "Turkmenistan", continent: "Asia", flagColors: ["green", "white", "red"], flagImage: "images/turkmenistan.png" },
  { name: "Tuvalu", continent: "Oceania", flagColors: ["blue", "yellow", "white", "red"], flagImage: "images/tuvalu.png" },
  { name: "Uganda", continent: "Africa", flagColors: ["black", "yellow", "red", "white"], flagImage: "images/uganda.png" },
  { name: "Ukraine", continent: "Europe", flagColors: ["blue", "yellow"], flagImage: "images/ukraine.png" },
  { name: "United Arab Emirates", continent: "Asia", flagColors: ["red", "green", "white", "black"], flagImage: "images/united-arab-emirates.png" },
  { name: "United Kingdom", continent: "Europe", flagColors: ["red", "white", "blue"], flagImage: "images/united-kingdom.png" },
  { name: "United States", continent: "North-America", flagColors: ["red", "white", "blue"], flagImage: "images/united-states.png" },
  { name: "Uruguay", continent: "South-America", flagColors: ["blue", "white", "yellow"], flagImage: "images/uruguay.png" },
  { name: "Uzbekistan", continent: "Asia", flagColors: ["blue", "white", "green", "red"], flagImage: "images/uzbekistan.png" },
  { name: "Vanuatu", continent: "Oceania", flagColors: ["red", "green", "black", "yellow"], flagImage: "images/vanuatu.png" },
  { name: "Vatican City", continent: "Europe", flagColors: ["yellow", "white"], flagImage: "images/vatican-city.png" },
  { name: "Venezuela", continent: "South-America", flagColors: ["yellow", "blue", "red"], flagImage: "images/venezuela.png" },
  { name: "Vietnam", continent: "Asia", flagColors: ["red", "yellow"], flagImage: "images/vietnam.png" },
  { name: "Yemen", continent: "Asia", flagColors: ["red", "white", "black"], flagImage: "images/yemen.png" },
  { name: "Zambia", continent: "Africa", flagColors: ["green", "red", "black", "orange"], flagImage: "images/zambia.png" },
  { name: "Zimbabwe", continent: "Africa", flagColors: ["green", "yellow", "red", "black", "white"], flagImage: "images/zimbabwe.png" }
];